language: python
python: 3.6
install:
  - pip uninstall numpy -y
  - pip install bandit codecov mypy pycodestyle safety typing
  - python setup.py install
script:
  - update-java-alternatives --list
  - pycodestyle --first --exclude venv,.eggs
  - safety check
  - bandit -r confluence
  - mypy --py2 . --ignore-missing-imports
  - sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
  - wget https://packages.atlassian.com/api/gpg/key/public
  - sudo apt-key add public
  - sudo sudo add-apt-repository ppa:rpardini/adoptopenjdk -y
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk adoptopenjdk-8-jdk-hotspot-installer
  - sudo update-java-alternatives --set /usr/lib/jvm/adoptopenjdk-8-jdk-hotspot
  - export PATH=/usr/lib/jvm/adoptopenjdk-8-jdk-hotspot/bin:$PATH
  - export JAVA_HOME="$(jrunscript -e 'java.lang.System.out.println(java.lang.System.getProperty("java.home"));')"
  - export CATALINA_OPTS="-Xms256m -Xmx1g"
  - atlas-version
  - ATLAS_OPTS="-Dallow.google.tracking=false" atlas-run-standalone --product confluence --version 6.15.0 --server localhost &>conf.txt &
  - CONFLUENCE_PID=$!
  - >
    until $(curl --fail http://localhost:1990/confluence); do
      sleep 5
    done
  - curl --fail http://localhost:1990/confluence/rest/api/space
  - wget http://localhost:1990/confluence -o home.html
  - ps -aux
  - tail -n 100 home.html
  - tail -n 100 conf.txt
  - tail -n 100 amps-standalone-confluence-6.15.0/target/confluence-LATEST.log
  - #python setup.py test --addopts "tests integration_tests --cov confluence"
  - kill -9 $CONFLUENCE_PID
  - rm -rf amps-standalone-confluence-6.15.0
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davetcode
  password:
    secure: XgEbiQwqG5x5nhypM8/FPbZR3SIGhwJHzY5wZ5v+ThGpWdJbGl1ntiZy/gwQyUVbLV0AAZFp2hm741JbstO6UH2nD2EObtOK6N/DLwRbf/JBiilnpWbzVtOXZrPuMOeary/M71jFc3EI0f+vO1lxEe0NURjePbj8L2h8HOzc8J8yzZp3XcbvBjPekIfu4bN6qUGl/JQhpAmIjEioea4oWf1PuRgSGcuCtttPaU4ihm9f7y0+L1RQWfOtT+iLc9PzRAK61JGlzU7Om0dWbkGw7YABBQ7FxNWFAmHRdNmDoP0K6Q2iMWyCdUuDdmlEupwCY21iGYSNrDPQ9e/JAJ4+EdphwgQpTVEMh7tTTbh58KhxvL4K0o+I9mZjF3IYNUTwyX1B1To51BSFn+ueTg8bgooxOk5uBEMe4axuMMgHYs1ZQ7fJ3F3fuHm++GP+nAaZTwjt6ICrWU1mTgg2wN91cX3JaP2YjGI3NPQH02BhTiHjZ8VL5erjIX7gKyQvrfzIL+3DPuJlxf67GRXETRvxC3dGTR6i7D2YlhNIaxSqX+Bf6oRERaeRouQy+xuhO5HoEH3cGAwAuEKayhCIM0frWKtg6u3mwXj9eclFG66QtQnj3pRIxd6zC2F+w6GVOYAmazs+ZqO5u+53x7bsTcO3aHv/wNVcmdu0J2H1QAvE/x8=
  on:
    tags: true
    repo: DaveTCode/confluence-python-lib
    condition: "$TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
